### PR TITLE
[Feature] Base layer extracted, added qwerty replacement

### PR DESCRIPTION
**Pull request by art4ride**

### CODE REVIEW

**Comment by minusfive** [comment]
@art4ride thanks! Will take a look and consider merging. ATM I'm still ironing out some annoying core behaviors, but def want QWERTY soon. I'd also ideally like to build both at once, without config tweaks.

**Review by minusfive — COMMENTED** [review]
So I've added a QWERTY branch as discussed. I'll probably go back and try and fiddle with the workflows to get this in a single branch somehow, but I agree this is the simplest solution at this stage.

Thank you so much for testing this out and giving it a shot, greatly appreciated.

Should we close this PR for now?

**Comment by art4ride** [comment]
The main goal for me was to actually introduce modularity.
e.g I use beakl myself. So that makes me easier to point keymap to use beakl and don't resolve merge conflicts whenever you introduce new changes to your base layer while inheriting changes for other layers/macros, behaviours etc.

**Comment by art4ride** [comment]
And I imagine that if someone wants to introduce another layout they could follow the same pattern without making bigger changes.

**Comment by art4ride** [comment]
Another benefit is when you develop changes you can quickly switch between old and new or compare them. by creating a new revision and pointing the base layer to it.
It is worth it to have all layers in separate files.

**Comment by minusfive** [comment]
Yeah, hear you. It occurred to me there may be another way of accomplishing this. Experimenting here, lmk what you think #10

Here's the action building both layouts/firmwares in parallel https://github.com/minusfive/zmk-config/actions/runs/5718961905

**Comment by art4ride** [comment]
#10 will fully cover this. closing

**Comment by minusfive** [comment]
Thanks again @art4ride !

**Pull request closed without merging**
